# HTTP (Tomcat) port
server:
  port: 8081

#Application name
spring:
  application:
    name: eureka-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
